import {
  SiTypescript,
  SiJavascript,
  SiReact,
  SiPython,
  SiHtml5,
  SiCss,
  SiSass,
  SiBootstrap,
  SiTailwindcss,
  SiAngular,
  SiVite,
  SiFlask,
  SiJest,
  SiJasmine,
  SiJira,
  SiPostman,
  SiSwagger,
  SiNpm,
  SiMysql,
  SiGit,
  SiJenkins,
  SiBitbucket,
  SiIntellijidea,
  SiMaterialdesign,
} from 'react-icons/si';
import { LuSquareCode } from 'react-icons/lu';

/**
 * Maps each skill name to a bundled icon component (react-icons).
 * Bundled locally so icons always render — no CDN, no broken images.
 */
export const skillIcons = {
  TypeScript: SiTypescript,
  'JavaScript (ES6)': SiJavascript,
  JSX: SiReact,
  Python: SiPython,
  HTML5: SiHtml5,
  CSS3: SiCss,
  'Sass / SCSS': SiSass,
  Bootstrap: SiBootstrap,
  'Tailwind CSS': SiTailwindcss,
  Angular: SiAngular,
  'Angular Material': SiMaterialdesign,
  React: SiReact,
  Vite: SiVite,
  Flask: SiFlask,
  Jest: SiJest,
  'Jasmine / Karma': SiJasmine,
  Git: SiGit,
  Jenkins: SiJenkins,
  Bitbucket: SiBitbucket,
  JIRA: SiJira,
  Postman: SiPostman,
  Swagger: SiSwagger,
  NPM: SiNpm,
  MySQL: SiMysql,
  IntelliJ: SiIntellijidea,
  'Visual Studio': LuSquareCode,
};
